version: '3.1'
services:
  oracle-db:
    image: gvenzl/oracle-xe:slim
    container_name: oracle12c-test
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=testuser
      - APP_USER_PASSWORD=testpwd
    volumes:
      - ./ddl:/opt/oracle/scripts/ddl
      - ./dml:/opt/oracle/scripts/dml
      - ./init/run-init.sh:/docker-entrypoint-initdb.d/run-init.sh
